{
 "title": "All Server Temperatures",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"BUCKETNAME\", tag: \"host\")\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hardware  Component Status",
   "type": "stat",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BUCKETNAME\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"hardware_status\" and\n    r.host == \"${host}\" and\n    r._field == \"health\"\n  )\n  |> map(fn: (r) => ({\n    r with\n    _value: if r._value == \"OK\" or r._value == \"LinkUp\" then 1.0 else 0.0,\n    _alias: if r.component == \"Disk\" then \"${r.name} (${r.serial} @ ${r.controller})\"\n            else if r.component == \"NIC\" then \"NIC ${r.name}\"\n            else if exists r.id then \"${r.component} ${r.name} (${r.id})\"\n            else \"${r.component} ${r.name}\"\n  }))\n  |> group(columns: [\"_alias\"])\n  |> keep(columns: [\"_value\", \"_alias\", \"_time\"])\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Temperature of All Sensors",
   "type": "stat",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BUCKETNAME\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"hardware_temperature\")\n  |> filter(fn: (r) => r.host == \"${host}\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> group(columns: [\"name\"])  // group by sensor name\n  |> keep(columns: [\"_time\", \"_value\", \"name\"])  // include the name in output\n\n\n"
    }
   ]
  },
  { "title": "CPU Health and State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Hardware Health Status",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"BUCKETNAME\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"hardware_status\" and r.host =~ /$host/)\n  |> group(columns: [\"host\"])\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"component\", \"id\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n:20)"
    }
   ]
  },
  {
   "title": "Temperature over Sensors",
   "type": "timeseries",
   "description": "Hardware Temperature ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "query": "from(bucket: \"BUCKETNAME\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"ipmi_sensor\" and r._field == \"value\")\n  |> filter(fn: (r) => contains(value: r.name, set: [\"01-inlet_ambient\", \"02-cpu_1_pkgtmp\", \"03-cpu_2_pkgtmp\", \"04-p1_dimm_1-6\", \"06-p1_dimm_7-12\", \"08-p2_dimm_1-6\", \"10-p2_dimm_7-12\", \"12-vr_p1\", \"13-vr_p2\", \"14-hd_max\"]))\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"name\"], valueColumn: \"_value\")\n  |> yield(name: \"sensor_values\")\n"
    }
   ]
  }
 ]
}